apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: nginx
    app: nginx
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: badaiv/nginx-lua:1
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        ports:
        - containerPort: 80